// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "fem_b_gui.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(500, 700, "Laminar Combustion Input File Generator");
    w = o; if (w) {/* empty */}
    { Fl_Group* o = new Fl_Group(15, 30, 475, 475, "Wall Settings");
      { Fl_Round_Button* o = new Fl_Round_Button(15, 40, 25, 25, "Isothermal");
        o->down_box(FL_ROUND_DOWN_BOX);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(15, 60, 25, 25, "Adiabatic");
        o->down_box(FL_ROUND_DOWN_BOX);
      } // Fl_Round_Button* o
      { new Fl_Input(335, 45, 130, 25, "Wall Temperature");
      } // Fl_Input* o
      { new Fl_Input(335, 70, 130, 25, "Inlet Temperature");
      } // Fl_Input* o
      { new Fl_Input(335, 95, 130, 25, "Inlet Pressure");
      } // Fl_Input* o
      { new Fl_Input(335, 120, 130, 25, "Outlet Pressure");
      } // Fl_Input* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 186, 475, 473, "Gas Settings");
      { new Fl_Input(335, 211, 130, 25, "Thermal Conductivity");
      } // Fl_Input* o
      { new Fl_Input(335, 235, 130, 25, "Density");
      } // Fl_Input* o
      { new Fl_Input(335, 260, 130, 25, "Specific Heat");
      } // Fl_Input* o
      { new Fl_Input(335, 285, 130, 25, "Viscosity");
      } // Fl_Input* o
      { new Fl_Input(335, 310, 130, 25, "Percent Fuel");
      } // Fl_Input* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 363, 475, 477, "Chemistry Settings");
      { new Fl_Input(335, 393, 130, 25, "Reaction Rate");
      } // Fl_Input* o
      { new Fl_Input(335, 415, 130, 25, "Enthalpy of Fuel");
      } // Fl_Input* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 475, 475, 475, "Mesh Settings");
      { new Fl_Input(335, 500, 130, 25, "User File");
      } // Fl_Input* o
      { new Fl_Input(335, 525, 130, 25, "Elements (X)");
      } // Fl_Input* o
      { new Fl_Input(335, 550, 130, 25, "Elements (Y)");
      } // Fl_Input* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 610, 475, 675, "Time Settings");
      { new Fl_Input(335, 635, 130, 25, "Duration");
      } // Fl_Input* o
      { new Fl_Input(335, 660, 130, 25, "Timestep");
      } // Fl_Input* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
