// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef fem_b_gui_h
#define fem_b_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Input.H>
Fl_Double_Window* make_window();
#endif
