// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "fem_b_gui.h"
#include <assert.h>
#include <fstream>
#include <string>

/**
 Function to print out input sub-block
*/
std::ostream& inblock(std::string name, int size, std::string ent[], std::string val[],std::ostream& out) {
  out << "[./" << name << "]\n";
  if (size > 0) {
  for (int ii=0;ii<size; ++ii) {
  	out << ent[ii] << " = " << val[ii] << "\n";
  }
  }
  
  out << "[../]\n";
}

Fl_Double_Window *main_window=(Fl_Double_Window *)0;

Fl_Group *bc_set=(Fl_Group *)0;

Fl_Round_Button *iso_button=(Fl_Round_Button *)0;

static void cb_iso_button(Fl_Round_Button*, void*) {
  if (iso_button->value()) {
adia_button->value(0);
} else {
adia_button->value(1);
};
}

Fl_Round_Button *adia_button=(Fl_Round_Button *)0;

static void cb_adia_button(Fl_Round_Button*, void*) {
  if (adia_button->value()) {
iso_button->value(0);
} else {
iso_button->value(1);
};
}

Fl_Input *wall_temp=(Fl_Input *)0;

Fl_Input *in_temp=(Fl_Input *)0;

Fl_Input *out_p=(Fl_Input *)0;

Fl_Group *gas_set=(Fl_Group *)0;

Fl_Input *gas_tc=(Fl_Input *)0;

Fl_Input *gas_dens=(Fl_Input *)0;

Fl_Input *gas_sh=(Fl_Input *)0;

Fl_Input *gas_visc=(Fl_Input *)0;

Fl_Input *gas_mf=(Fl_Input *)0;

Fl_Group *chem_set=(Fl_Group *)0;

Fl_Input *rx_rate=(Fl_Input *)0;

Fl_Input *fuel_h=(Fl_Input *)0;

Fl_Group *mesh_set=(Fl_Group *)0;

Fl_Input *x_elem=(Fl_Input *)0;

Fl_Input *y_elem=(Fl_Input *)0;

Fl_Input *xmax=(Fl_Input *)0;

Fl_Input *ymax=(Fl_Input *)0;

Fl_Group *time_set=(Fl_Group *)0;

Fl_Input *duration=(Fl_Input *)0;

Fl_Input *timestep=(Fl_Input *)0;

Fl_Button *submit=(Fl_Button *)0;

static void cb_submit(Fl_Button*, void*) {
  std::string Tw_str, Ti_str, TC_str, dens_str, SH_str, visc_str, MF_str; //Po_str
std::string RX_str, Hfuel_str, El_x_str, El_y_str, dur_str, timestep_str, xmax_str, ymax_str;
std::string input_str, mesh_str;
bool adia_iso;

if (iso_button->value()) {
adia_iso = false;
} else if (adia_button->value()) {
adia_iso = true;
} else {
adia_iso = false;
}

if (wall_temp->value()) {
Tw_str = std::string(wall_temp->value());
} else {
Tw_str="300";
}

if (in_temp->value()) {
Ti_str = std::string( in_temp->value());
} else {
Ti_str = std::string("300");
}

// if (out_p->value()) {
// Po_str = std::string( out_p->value());
// } else {
// Po_str = std::string("300");
// }

if (gas_tc->value()) {
TC_str = std::string("'")+std::string( gas_tc->value())+std::string("'");
} else {
TC_str = std::string("300");
}

if (gas_dens->value()) {
dens_str = std::string("'")+std::string( gas_dens->value())+std::string("'");
} else {
dens_str = std::string("300");
}

if (gas_sh->value()) {
SH_str = std::string("'")+std::string( gas_sh->value())+std::string("'");
} else {
SH_str = std::string("300");
}

if (gas_visc->value()) {
visc_str = std::string("'")+std::string( gas_visc->value())+std::string("'");
} else {
visc_str = std::string("300");
}

if (gas_mf->value()) {
MF_str = std::string( gas_mf->value());
} else {
MF_str = std::string("300");
}

if (rx_rate->value()) {
RX_str = std::string( rx_rate->value());
} else {
RX_str = std::string("300");
}

if (fuel_h->value()) {
Hfuel_str = std::string( fuel_h->value());
} else {
Hfuel_str = std::string("300");
}

if (x_elem->value()) {
El_x_str = std::string( x_elem->value());
} else {
El_x_str = std::string("300");
}

if (y_elem->value()) {
El_y_str = std::string( y_elem->value());
} else {
El_x_str = std::string("300");
}

if (xmax->value()) {
xmax_str = std::string( xmax->value());
} else {
xmax_str = std::string("300");
}

if (ymax->value()) {
ymax_str = std::string( ymax->value());
} else {
ymax_str = std::string("300");
}


if (duration->value()) {
dur_str = std::string( duration->value());
} else {
dur_str = std::string("300");
}

if (timestep->value()) {
timestep_str = std::string(timestep->value());
} else {
timestep_str = std::string("300");
}

if (in_file->value() > 0) {
input_str = std::string(in_file->text(in_file->value()));
} else if (new_file->value()) {
input_str = std::string(new_file->value());
} else {
input_str = std::string("default.i");
}

if (mesh_file->value() > 0) {
mesh_str = std::string(mesh_file->text(mesh_file->value()));
} else {
mesh_str = std::string("default_mesh.e");
}

std::ofstream outfile(input_str,std::ios::out);

assert(outfile.is_open());

// Mesh

outfile << "[Mesh]\n";

if (mesh_file->value() == 0 && bool(x_elem->value())&& bool(x_elem->value())) {
	outfile << "type = GeneratedMesh\n";
	outfile << "dim = 2\n";
	outfile << "nx = " << El_x_str << "\n";
	outfile << "ny = " << El_y_str << "\n";
	outfile << "nz = 0\n\n";
	outfile << "xmax = " << xmax_str << "\n";
	outfile << "ymax = " << ymax_str << "\n";
	outfile << "zmax = 0\n";
	outfile << "elem_type = TRI3\n";
} else {
	outfile << "file = " << mesh_str << "\n";
}

outfile << "[]\n\n";

outfile << "[Variables]\n[./temp]\n[../]\n[]\n\n";

outfile << "[Kernels]\n[./hc]\n type = HeatConduction\n variable = temp\n[../]\n\n";

outfile << "[./HeatTdot]\ntype = HeatConductionTimeDerivative\nvariable = temp\n[../]\n[]\n\n";

outfile << "[BCs]\n";

if (adia_iso) {

}

outfile << "[Materials]\n";

std::string matnames[4] = {std::string("type"), std::string("prop_names"),std::string("prop_values"),std::string("block")};
std::string kvals[4] = {std::string("GenericConstantMaterial"),std::string("'thermal_conductivity'"),TC_str,std::string("0")};
std::string cpvals[4] = {std::string("GenericConstantMaterial"),std::string("'specific_heat'"),SH_str,std::string("0")};
std::string rhovals[4] = {std::string("GenericConstantMaterial"),std::string("'density'"),dens_str,std::string("0")};
inblock(std::string("k"),4,matnames,kvals,outfile);
inblock(std::string("cp"),4,matnames,cpvals,outfile);
inblock(std::string("rho"),4,matnames,rhovals,outfile);
outfile << "[]\n\n";

outfile << "[Executioner]\n";
outfile << "type = Transient\nsolve_type = 'PJFNK'\n";
outfile << "num_steps = " << dur_str << "\n";
outfile << "dt = " << timestep_str << "\n";
outfile << "[]\n\n";

outfile << "[Outputs]\nexecute_on = 'timestep_end'\nexodus = true\n[]";
}

Fl_File_Browser *in_file=(Fl_File_Browser *)0;

Fl_File_Browser *mesh_file=(Fl_File_Browser *)0;

Fl_Input *new_file=(Fl_Input *)0;

Fl_Double_Window* make_window() {
  { main_window = new Fl_Double_Window(678, 749, "Laminar Combustion Input File Generator");
    { bc_set = new Fl_Group(190, 30, 475, 475, "Boundary Conditions");
      { iso_button = new Fl_Round_Button(510, 120, 25, 25, "Isothermal");
        iso_button->down_box(FL_ROUND_DOWN_BOX);
        iso_button->callback((Fl_Callback*)cb_iso_button);
        iso_button->align(Fl_Align(FL_ALIGN_LEFT));
        iso_button->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* iso_button
      { adia_button = new Fl_Round_Button(510, 140, 25, 25, "Adiabatic");
        adia_button->down_box(FL_ROUND_DOWN_BOX);
        adia_button->callback((Fl_Callback*)cb_adia_button);
        adia_button->align(Fl_Align(FL_ALIGN_LEFT));
      } // Fl_Round_Button* adia_button
      { wall_temp = new Fl_Input(510, 45, 130, 25, "Wall Temperature");
      } // Fl_Input* wall_temp
      { in_temp = new Fl_Input(510, 70, 130, 25, "Inlet Temperature");
      } // Fl_Input* in_temp
      { out_p = new Fl_Input(510, 95, 130, 25, "Outlet Pressure");
      } // Fl_Input* out_p
      bc_set->end();
    } // Fl_Group* bc_set
    { gas_set = new Fl_Group(185, 186, 475, 473, "Gas Settings");
      { gas_tc = new Fl_Input(510, 211, 130, 25, "Thermal Conductivity");
      } // Fl_Input* gas_tc
      { gas_dens = new Fl_Input(510, 235, 130, 25, "Density");
      } // Fl_Input* gas_dens
      { gas_sh = new Fl_Input(510, 260, 130, 25, "Specific Heat");
      } // Fl_Input* gas_sh
      { gas_visc = new Fl_Input(510, 285, 130, 25, "Viscosity");
      } // Fl_Input* gas_visc
      { gas_mf = new Fl_Input(510, 310, 130, 25, "Percent Fuel");
      } // Fl_Input* gas_mf
      gas_set->end();
    } // Fl_Group* gas_set
    { chem_set = new Fl_Group(185, 363, 475, 477, "Chemistry Settings");
      { rx_rate = new Fl_Input(510, 393, 130, 25, "Reaction Rate");
      } // Fl_Input* rx_rate
      { fuel_h = new Fl_Input(510, 415, 130, 25, "Enthalpy of Fuel");
      } // Fl_Input* fuel_h
      chem_set->end();
    } // Fl_Group* chem_set
    { mesh_set = new Fl_Group(185, 475, 475, 475, "Mesh Settings");
      { x_elem = new Fl_Input(510, 490, 130, 25, "Elements (X)");
      } // Fl_Input* x_elem
      { y_elem = new Fl_Input(510, 515, 130, 25, "Elements (Y)");
      } // Fl_Input* y_elem
      { xmax = new Fl_Input(510, 540, 130, 25, "X Max");
      } // Fl_Input* xmax
      { ymax = new Fl_Input(510, 565, 130, 25, "Y Max");
      } // Fl_Input* ymax
      mesh_set->end();
    } // Fl_Group* mesh_set
    { time_set = new Fl_Group(185, 605, 475, 675, "Time Settings");
      { duration = new Fl_Input(510, 630, 130, 25, "Number of Steps");
      } // Fl_Input* duration
      { timestep = new Fl_Input(510, 655, 130, 25, "Timestep");
      } // Fl_Input* timestep
      time_set->end();
    } // Fl_Group* time_set
    { submit = new Fl_Button(527, 708, 100, 25, "Submit");
      submit->callback((Fl_Callback*)cb_submit);
    } // Fl_Button* submit
    { in_file = new Fl_File_Browser(26, 105, 310, 235, "Input File Location");
      in_file->load(".");
      in_file->type(FL_HOLD_BROWSER);
    } // Fl_File_Browser* in_file
    { mesh_file = new Fl_File_Browser(26, 424, 310, 235, "Mesh File Location");
      mesh_file->load(".");
      mesh_file->type(FL_HOLD_BROWSER);
    } // Fl_File_Browser* mesh_file
    { new_file = new Fl_Input(177, 364, 161, 25, "New Input File Name");
    } // Fl_Input* new_file
    main_window->end();
  } // Fl_Double_Window* main_window
  return main_window;
}
