#include "FemBApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<FemBApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

FemBApp::FemBApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  FemBApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  FemBApp::associateSyntax(_syntax, _action_factory);
}

FemBApp::~FemBApp()
{
}

// External entry point for dynamic application loading
extern "C" void FemBApp__registerApps() { FemBApp::registerApps(); }
void
FemBApp::registerApps()
{
  registerApp(FemBApp);
}

// External entry point for dynamic object registration
extern "C" void FemBApp__registerObjects(Factory & factory) { FemBApp::registerObjects(factory); }
void
FemBApp::registerObjects(Factory & /*factory*/)
{
}

// External entry point for dynamic syntax association
extern "C" void FemBApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { FemBApp::associateSyntax(syntax, action_factory); }
void
FemBApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
